import React from "react";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { 
  Shield, 
  AlertTriangle, 
  Download, 
  RotateCcw,
  CheckCircle,
  XCircle,
  HelpCircle
} from "lucide-react";

import ResultsSummary from "./ResultsSummary";
import MatchesTable from "./MatchesTable";
import RiskAssessment from "./RiskAssessment";
import ExtractedDetails from "./ExtractedDetails";

/**
 * AnalysisResults Component
 * 
 * Displays the complete analysis results for a property verification including:
 * - Risk level assessment with visual indicators
 * - Property details extracted from the listing
 * - Cross-platform matches found
 * - Fraud indicators and warnings
 * - Action buttons for downloading report and starting new analysis
 * 
 * @param {Object} results - The analysis results object containing risk level, matches, etc.
 * @param {Function} onNewAnalysis - Callback function to initiate a new property analysis
 * @returns {JSX.Element} The complete analysis results display
 */
export default function AnalysisResults({ results, onNewAnalysis }) {
  /**
   * Returns the appropriate CSS classes for risk level styling
   * @param {string} riskLevel - The risk level (All Clear, Caution, High Risk)
   * @returns {string} CSS classes for styling the risk badge
   */
  const getRiskColor = (riskLevel) => {
    switch (riskLevel) {
      case 'All Clear': return 'bg-green-100 text-green-800 border-green-200';
      case 'Caution': return 'bg-yellow-100 text-yellow-800 border-yellow-200';
      case 'High Risk': return 'bg-red-100 text-red-800 border-red-200';
      default: return 'bg-gray-100 text-gray-800 border-gray-200';
    }
  };

  /**
   * Returns the appropriate icon component for the risk level
   * @param {string} riskLevel - The risk level (All Clear, Caution, High Risk)
   * @returns {JSX.Element} The icon component for the risk level
   */
  const getRiskIcon = (riskLevel) => {
    switch (riskLevel) {
      case 'All Clear': return <CheckCircle className="w-5 h-5" />;
      case 'Caution': return <HelpCircle className="w-5 h-5" />;
      case 'High Risk': return <AlertTriangle className="w-5 h-5" />;
      default: return <Shield className="w-5 h-5" />;
    }
  };

  /**
   * Generates and downloads a detailed verification report as a text file
   * Contains all analysis results, property details, and matches found
   */
  const handleDownloadReport = () => {
    const { extracted_details, matches_found, risk_level, summary, fraud_indicators } = results;
    
    let reportContent = `
PropertyGuard Verification Report
=================================
Analysis Date: ${new Date().toLocaleDateString()}
Risk Level: ${risk_level?.toUpperCase()}

Summary:
--------
${summary}

Fraud Indicators / Inconsistencies:
-----------------------------------
${fraud_indicators?.length > 0 ? fraud_indicators.map(indicator => `• ${indicator}`).join('\n') : 'None detected'}

Verified Listing Details (from your submitted URL):
---------------------------------------------------
Title: ${extracted_details.listing_title}
Address: ${extracted_details.address}
Price: ${extracted_details.price}
Agent: ${extracted_details.agent_name}
Platform: ${extracted_details.source_platform}
Features: ${extracted_details.features?.join(', ')}

Cross-Platform Matches Found: ${matches_found?.length || 0}
------------------------------------
`;
    
    if (matches_found && matches_found.length > 0) {
      matches_found.forEach((match, index) => {
        reportContent += `
Match ${index + 1}:
  Platform: ${match.platform}
  Title: ${match.listing_title}
  Price: ${match.price}
  Agent: ${match.agent_name}
  Flags: ${match.suspicious_flags?.join(', ') || 'None'}
  URL: ${match.listing_url}
`;
      });
    } else {
      reportContent += "No other listings found for this property.";
    }

    reportContent += `
---
Generated by PropertyGuard - Canadian Real Estate Fraud Detection
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `PropertyGuard-Report-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Calculate warning states based on unavailable listings
  const unavailableCount = results.matches_found?.filter(match =>
    match.suspicious_flags?.some(flag => 
      flag.toLowerCase().includes('inactive') || flag.toLowerCase().includes('removed')
    )
  ).length || 0;

  const totalMatches = results.matches_found?.length || 0;
  const showHighLevelWarning = totalMatches > 0 && unavailableCount === totalMatches;
  const showCautionWarning = totalMatches > 1 && unavailableCount > 0 && !showHighLevelWarning;

  return (
    <div className="space-y-4 sm:space-y-6">
      {/* Header with Risk Level */}
      <Card className="border-none shadow-xl">
        <CardHeader className="text-center pb-4 sm:pb-6">
          <div className="flex justify-center mb-3 sm:mb-4">
            <Badge className={`px-3 sm:px-4 py-2 text-base sm:text-lg font-semibold border ${getRiskColor(results.risk_level)}`}>
              {getRiskIcon(results.risk_level)}
              <span className="ml-2">{results.risk_level?.toUpperCase()}</span>
            </Badge>
          </div>
          <CardTitle className="text-xl sm:text-2xl font-bold text-gray-900 mb-2">
            Verification Complete
          </CardTitle>
          <p className="text-sm sm:text-base text-gray-600 px-2">
            Found {results.matches_found?.length || 0} potential matches across Canadian real estate platforms.
          </p>
        </CardHeader>
      </Card>

      {/* Testing Stats Section */}
      <Card className="border-none shadow-lg bg-gradient-to-r from-blue-50 to-indigo-50">
        <CardHeader className="text-center pb-4">
          <div className="text-sm font-semibold text-blue-800 uppercase tracking-wider mb-3">
            TESTING STATS
          </div>
          <div className="grid grid-cols-2 gap-4 max-w-sm mx-auto">
            <div>
              <div className="text-gray-600 text-sm">URLs Analyzed</div>
              <div className="font-bold text-2xl text-blue-600">47</div>
            </div>
            <div>
              <div className="text-gray-600 text-sm">Issues Found</div>
              <div className="font-bold text-2xl text-red-600">12</div>
            </div>
          </div>
          <div className="flex items-center justify-center gap-2 mt-4 text-xs text-gray-600">
            <Shield className="w-4 h-4" />
            <span>Testing phase - Demo scenarios available</span>
          </div>
        </CardHeader>
      </Card>

      {/* Action Buttons */}
      <div className="flex flex-col sm:flex-row gap-3 sm:gap-4 justify-center px-4">
        <Button
          onClick={handleDownloadReport}
          className="w-full sm:w-auto bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-sm sm:text-base"
        >
          <Download className="w-4 h-4 mr-2" />
          Download Report
        </Button>
        <Button
          onClick={onNewAnalysis}
          variant="outline"
          className="w-full sm:w-auto border-red-200 text-red-700 hover:bg-red-50 text-sm sm:text-base"
        >
          <RotateCcw className="w-4 h-4 mr-2" />
          New Verification
        </Button>
      </div>

      {/* High-level Unavailable Warning */}
      {showHighLevelWarning && (
        <Alert variant="destructive" className="border-red-200 bg-red-50">
          <AlertTriangle className="h-4 w-4 text-red-600" />
          <AlertDescription className="text-red-800 text-sm sm:text-base">
            <strong>Warning: Property Not Found.</strong> The listing appears to have been removed from all platforms we checked. The links may be outdated or the property is no longer for sale.
          </AlertDescription>
        </Alert>
      )}
      {showCautionWarning && (
        <Alert variant="destructive" className="border-orange-200 bg-orange-50">
          <AlertTriangle className="h-4 w-4 text-orange-600" />
          <AlertDescription className="text-orange-800 text-sm sm:text-base">
            <strong>Caution:</strong> This property is no longer listed on {unavailableCount} out of {totalMatches} matched platforms. Please verify its status before proceeding.
          </AlertDescription>
        </Alert>
      )}

      {/* Results Summary */}
      <ResultsSummary summary={results.summary} />

      {/* Risk Assessment */}
      <RiskAssessment 
        riskLevel={results.risk_level}
        fraudIndicators={results.fraud_indicators}
      />
      
      {/* Extracted Details */}
      <ExtractedDetails details={results.extracted_details} originalUrl={results.listing_url} />

      {/* Matches Table */}
      <MatchesTable matches={results.matches_found} />

      {/* Warning if High Risk */}
      {results.risk_level === 'High Risk' && (
        <Alert variant="destructive" className="border-red-200 bg-red-50">
          <AlertTriangle className="h-4 w-4" />
          <AlertDescription className="text-red-800 text-sm sm:text-base">
            <strong>⚠️ HIGH RISK DETECTED:</strong> This property listing shows multiple red flags 
            that suggest potential fraud. We strongly recommend verifying all details with licensed 
            real estate professionals and conducting additional due diligence before proceeding.
          </AlertDescription>
        </Alert>
      )}
    </div>
  );
}
