# Generated by Django 4.2.7 on 2025-07-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_add_bio_to_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
