# Generated by Django 4.2.7 on 2025-06-27 16:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('social_media', 'Social Media'), ('seo', 'SEO'), ('blog', 'Blog'), ('video', 'Video'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price in CAD', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Per Hour'), ('monthly', 'Per Month'), ('custom', 'Custom Quote'), ('tiered', 'Tiered Pricing')], default='custom', max_length=20),
        ),
        migrations.CreateModel(
            name='ServicePricingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in CAD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('period', models.CharField(choices=[('one_time', 'One Time'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='one_time', max_length=20)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_popular', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_options', to='core.service')),
            ],
            options={
                'ordering': ['order', 'price'],
            },
        ),
    ]
