# Generated by Django 4.2.7 on 2025-07-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_portfoliocategory_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='content_type',
            field=models.CharField(choices=[('post', 'Post'), ('video', 'Video'), ('blog', 'Blog'), ('email', 'Email'), ('technology', 'Technology')], default='post', max_length=20),
        ),
    ]
