# Generated by Django 4.2.7 on 2025-07-08 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_portfolio_image'),
        ('core', '0008_portfolio_cloudinary_image_id_alter_portfolio_image'),
    ]

    operations = [
    ]
