# Generated by Django 4.2.7 on 2025-07-11 15:14

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20250708_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cloudinary_image_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
