# Generated by Django 4.2.7 on 2025-07-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_project_cloudinary_image_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='content_type',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
