# Generated by Django 4.2.7 on 2025-07-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_portfolio_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='bio',
            field=models.TextField(blank=True, help_text='Optional bio or extra info about the portfolio.', null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='content_type',
            field=models.CharField(choices=[('post', 'Post'), ('video', 'Video'), ('blog', 'Blog'), ('email', 'Email'), ('technology', 'Technology')], default='post', max_length=20),
        ),
    ]
