# Generated by Django 4.2.7 on 2025-07-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_portfolio_type'),
        ('core', '0011_portfolio_portfolio_type_project_portfolio_type'),
    ]

    operations = [
    ]
