# Generated by Django 4.2.7 on 2025-07-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20250714_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cloudinary_image_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for the image', max_length=255, null=True),
        ),
    ]
