# Generated by Django 4.2.7 on 2025-07-15 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20250714_2208'),
        ('core', '0012_portfolio_bio_alter_portfolio_content_type'),
    ]

    operations = [
    ]
