# Generated by Django 4.2.7 on 2025-07-17 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20250715_0642'),
        ('core', '0013_service_cloudinary_image_id'),
    ]

    operations = [
    ]
