# Generated by Django 4.2.7 on 2025-07-18 01:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20250718_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cloudinary_image_id',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a video file (MP4, MOV, AVI, WEBM)', null=True, upload_to='portfolio_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
