# Generated by Django 4.2.7 on 2025-07-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_bio_field'),
    ]

    operations = [
        # This migration is a no-op because the video_file field doesn't exist in the database
        # The field was added in migration 0015 but was never applied to the database
    ]

#-------------------------------------