# Generated by Django 4.2.7 on 2025-07-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_portfolio_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_name',
            field=models.CharField(default='Custom Service', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='pricing_plan_name',
            field=models.CharField(default='Custom Plan', max_length=200),
            preserve_default=False,
        ),
    ]
